### ISSUE TITLE
When using InMemorySessionStore stored values are not persisted across requests

### ISSUE THREAD

**Issue by 5bodnar** [micronaut-projects/micronaut-session#116]
### Expected Behavior

Following the tutorial  here https://micronaut-projects.github.io/micronaut-session/snapshot/guide/, I've attempted to get basic in-memory sessions working on a micronaut application I am working on. I have tried storing a simple int counter in a controller method, where that method is passed a Session argument. The code looks as follows (edited)

@Post(uri="/increment")
String increment(Session session, @Body Map<String, Object> json) {
    // For debugging sessions with micronaut
    println "is new: " + session.isNew()
    
    int counter = session.get("counter").orElse(0).value
    println "Counter before: " + counter
    session.put("counter", counter + 1)
    println "Counter after:" +  session.get("counter").value
}

I expected .isNew() to print true the first time I access the increment endpoint (via browser). I also expected the counter to increment by 1 each time the endpoint is accessed.

### Actual Behaviour

Each time I access the endpoint, a new Session object appears to be passed in as an argument, so that .isNew() is always true, and the counter variable never grows beyond 1.

I feel like I am maybe missing something obvious, but I can't find a lot of documentation or working examples of the InMemorySessionStore with corresponding application.yml, and am at a loss. Any help would be super appreciated!

### Steps To Reproduce

**1. Edit build.gradle to have following dependencies**

dependencies {
       implementation("io.micronaut:micronaut-http-client")
       implementation("io.micronaut.groovy:micronaut-runtime-groovy")
       implementation("ch.qos.logback:logback-classic")
	implementation("ch.qos.logback:logback-core")
        implementation("io.micronaut:micronaut-validation")
	implementation("io.micronaut:micronaut-session:3.10.1")
	
	testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.0'
        testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.0'
	
	implementation 'org.hibernate:hibernate-core:5.4.23.Final'
	implementation 'org.postgresql:postgresql:42.6.0'
}

**2. Add session configuration to application.yml**

micronaut:
  application:
    name: increment-example
  
  server:
      cors:
        enabled: true
  
  session:
    http:
      cookie: false
      header: true

**3. Start the application with .gradlew run**

**4. Contact the endpoint at http://localhost:8080/example/increment from web browser with a jquery HTTP Post

### Environment Information

Micronaut Version 4.1.4
Java 8.0.302-open  (from sdkman)
Gradle 6.9.2
Groovy Version: 4.0.15
Ubuntu 22.04

### Version

4.1.4

**Comment by eahrold** [comment]
The jquery Post requests may need ‘with credentials’ variant set in order to send the session cookie along with the request.  

Check your session id each time to see if that is changing.

**Comment by 5bodnar** [comment]
Thank you very much for the hint! I gave it a try this morning and was able to get it working by combining application.yml with cookies set to true

session:
    http:
      cookie: true
      header: true
     
with adding the 'with credentials variant' you suggested, like this

$.ajax({
	type: "POST",
	url: url,
	contentType: 'application/json; charset=utf-8',
	data: JSON.stringify(payload),
	
	xhrFields: {
		      withCredentials: true
		  },

	success(data) {},

	error(XMLHttpRequest, textStatus, errorThrown) {}
});
}

I don't fully understand why it doesn't work with cookies disabled and using only the header, but cookies fits with our use case and I have it working, so again, thanks a bunch! :)

**Comment by 5bodnar** [comment]
As a follow up, would anyone have a similar hint for getting Cookies to work with micronaut's HttpClient ? I looked around a bit on the web, and it seems like support for cookies was added

https://github.com/micronaut-projects/micronaut-core/issues/3082

However, calling an HttpRequest's .getCookies() method throws an UnsupportedOperationException.

I'm hoping to use this in a junit test.

**Comment by 5bodnar** [comment]
FWIW, I was able to solve this issue by replacing the Micronaut HttpClient and related classes with Java 11's java.net.http.HttpClient, HttpRequest, and so on. This link on stackoverflow was helpful

https://stackoverflow.com/questions/66388231/json-object-to-body-publisher

The gist of it is setting up an HttpClient like so

```
CookieHandler.setDefault(new CookieManager());

HttpClient client = HttpClient.newBuilder()
                .cookieHandler(CookieHandler.getDefault())
                .connectTimeout(Duration.ofSeconds(10))
                .build();
```

and then reusing the client in requests.
